
package Interface;

import Process.DeTai;
import Process.Khoa;
import Process.PhanCong;
import Process.SinhVien;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class fmMain extends javax.swing.JFrame {
    Map<String, String> listSinhVien = new HashMap<>();
    Map<String, Integer> listDeTai = new HashMap<>();
    private final PhanCong phanCong = new PhanCong();
    private final DeTai deTai = new DeTai();
    private final SinhVien sinhVien = new SinhVien();
    private final DefaultTableModel tableModel = new DefaultTableModel();

    public fmMain() throws SQLException {
        initComponents();
        String[] colsName = {"Mã Sinh Viên", "STT Đề Tài", "Mã GV Hướng Dẫn", "Mã GV Phản Biện", "Điểm GV Hướng Dẫn", "Điểm GV Phản Biện", "Nhận Xét GV Hướng Dẫn", "Nhận Xét GV Phản Biện"};
        // đặt tiêu đề cột cho tableModel
        tableModel.setColumnIdentifiers(colsName);
        // kết nối jtable với tableModel
        tableDanhSach.setModel(tableModel);
        // Show combobox
        showSinhVien();
        showDeTai();
        //gọi hàm ShowData để đưa dữ liệu vào tableModel
        ShowData();
        //goi Ham xoa trang cac TextField
        setNull();
        
    }
    
    public void showSinhVien() throws SQLException {
        listSinhVien = new HashMap<>();
        ResultSet resultSet = sinhVien.ShowSinhVien();
        try {
            while (resultSet.next()) {
                listSinhVien.put(resultSet.getString(2), resultSet.getString(1));
            }
            for (String s : listSinhVien.keySet()) {
                boxSinhVien.addItem(s);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void showDeTai() throws SQLException {
        listDeTai = new HashMap<>();
        ResultSet resultSet = deTai.ShowDeTai();
        try {
            while (resultSet.next()) {
                listDeTai.put(resultSet.getString(2), resultSet.getInt(1));
            }
            for (String s : listDeTai.keySet()) {
                boxDeTai.addItem(s);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void ShowData() throws SQLException {
        ResultSet result = phanCong.ShowPhanCong();
        try {
            while (result.next()) {
                String rows[] = new String[8];
                rows[0] = result.getString(1);
                rows[1] = result.getString(2);
                rows[2] = result.getString(3);
                rows[3] = result.getString(4);
                rows[4] = result.getString(5);
                rows[5] = result.getString(6);
                rows[6] = result.getString(7);
                rows[7] = result.getString(8);
                tableModel.addRow(rows);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    //Ham xoa cac TextField
    private void setNull() {
        //Xoa trang cac JtextField
        this.txtDiemGVHD.setValue(0);
        this.txtDiemGVPB.setValue(0);
        this.txtMaGVHD.setText(null);
        this.txtMaGVPB.setText(null);
        this.textNXGVHD.setText(null);
        this.textNXGVPB.setText(null);
        this.boxDeTai.setSelectedIndex(-1);
        this.boxSinhVien.setSelectedIndex(-1);
    }

    void clear() {
        //Lay chi so dong cuoi cung
        int n = tableDanhSach.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tableModel.removeRow(i);//Remove tung dong
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelThongTin = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boxSinhVien = new javax.swing.JComboBox<>();
        txtMaGVHD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDiemGVHD = new javax.swing.JSpinner();
        boxDeTai = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaGVPB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDiemGVPB = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        textNXGVPB = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textNXGVHD = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();
        panelDanhSach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDanhSach = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSinhVien = new javax.swing.JMenuItem();
        itemGiaoVien = new javax.swing.JMenuItem();
        itemKhoa = new javax.swing.JMenuItem();
        itemDeTai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ứng Dụng Quản Lý Đồ Án");
        setBackground(new java.awt.Color(102, 102, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1280, 740));
        setPreferredSize(new java.awt.Dimension(1366, 653));
        setResizable(false);

        panelThongTin.setBackground(new java.awt.Color(255, 255, 204));
        panelThongTin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelThongTin.setToolTipText("");
        panelThongTin.setName(""); // NOI18N

        btnAdd.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 0, 0));
        btnReset.setText("Nhập Lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông Tin Chi Tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mã Sinh Viên:");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("STT Đề Tài:");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nhận Xét GVPB:");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nhận Xét GVHD:");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Điểm GVHD:");

        txtDiemGVHD.setModel(new javax.swing.SpinnerNumberModel());

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Mã GVHD:");

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Mã GVPB:");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Điểm GVPB:");

        txtDiemGVPB.setModel(new javax.swing.SpinnerNumberModel());

        textNXGVPB.setColumns(20);
        textNXGVPB.setRows(5);
        jScrollPane2.setViewportView(textNXGVPB);

        textNXGVHD.setColumns(20);
        textNXGVHD.setRows(5);
        jScrollPane3.setViewportView(textNXGVHD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxDeTai, 0, 391, Short.MAX_VALUE)
                            .addComponent(txtMaGVHD)
                            .addComponent(boxSinhVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiemGVHD)
                            .addComponent(txtMaGVPB)
                            .addComponent(txtDiemGVPB))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(boxSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(boxDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMaGVHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaGVPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDiemGVHD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtDiemGVPB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExit.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setText("THOÁT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThongTinLayout = new javax.swing.GroupLayout(panelThongTin);
        panelThongTin.setLayout(panelThongTinLayout);
        panelThongTinLayout.setHorizontalGroup(
            panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelThongTinLayout.setVerticalGroup(
            panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinLayout.createSequentialGroup()
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelThongTinLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThongTinLayout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelDanhSach.setBackground(new java.awt.Color(255, 255, 204));

        tableDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sinh Viên", "STT Đề Tài", "Mã GV Hướng Dẫn", "Mã GV Phản Biện", "Điểm GV Hướng Dẫn", "Điểm GV Phản Biện", "Nhận Xét GV Hướng Dẫn", "Nhận Xét GV Phản Biện"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDanhSach);

        javax.swing.GroupLayout panelDanhSachLayout = new javax.swing.GroupLayout(panelDanhSach);
        panelDanhSach.setLayout(panelDanhSachLayout);
        panelDanhSachLayout.setHorizontalGroup(
            panelDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        panelDanhSachLayout.setVerticalGroup(
            panelDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        jMenu1.setText("Quản Lý");

        itemSinhVien.setText("Sinh Viên");
        itemSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSinhVienActionPerformed(evt);
            }
        });
        jMenu1.add(itemSinhVien);

        itemGiaoVien.setText("Giáo Viên");
        itemGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGiaoVienActionPerformed(evt);
            }
        });
        jMenu1.add(itemGiaoVien);

        itemKhoa.setText("Khóa");
        itemKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKhoaActionPerformed(evt);
            }
        });
        jMenu1.add(itemKhoa);

        itemDeTai.setText("Đề tài");
        itemDeTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeTaiActionPerformed(evt);
            }
        });
        jMenu1.add(itemDeTai);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelThongTin.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        setNull();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String idSV = listSinhVien.get(boxSinhVien.getSelectedItem().toString());
        int idDT = listDeTai.get(boxDeTai.getSelectedItem().toString());
        try {
            if (idSV.length() == 0) {
                JOptionPane.showMessageDialog(null, "Chọn để xóa",
                        "Thông báo", 1);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Muốn xóa sinh vien " + idSV + " thuoc de tai"+idDT+" ? ", "Thong bao", 2) == 0) {
                    phanCong.DeleteData(idSV,idDT);//goi ham xoa du lieu theo ma loai
                    clear();//Xoa du lieu trong tableModel
                    ShowData();//Do du lieu vao table Model
                    setNull();//Xoa trang Textfield
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Xóa thất bại", "Thông báo", 1);
        }         
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String idSV = listSinhVien.get(boxSinhVien.getSelectedItem().toString());
        int idDT = listDeTai.get(boxDeTai.getSelectedItem().toString());
        try {
            if (idSV.length() == 0) {
                JOptionPane.showMessageDialog(null, "Chọn giáo viên để sửa",
                        "Thông báo", 1);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa " + idSV + " thuộc "+ idDT +" ? ", "Thong bao", 2) == 0) {
                    phanCong.EditData(listSinhVien.get(boxSinhVien.getSelectedItem().toString()), listDeTai.get(boxDeTai.getSelectedItem().toString()),txtMaGVHD.getText(), txtMaGVPB.getText(),(Integer)txtDiemGVHD.getValue(),(Integer)txtDiemGVPB.getValue(),textNXGVHD.getText(),textNXGVPB.getText());
                }
            }
            clear();
            ShowData();
            setNull();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "sua thất bại", "Thông báo", 1);
        }     

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //thêm mới
        try {
            if (boxDeTai.getSelectedItem() == null || boxSinhVien.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "????", "Thông báo", 1);
            } else if (phanCong.tontaima(listSinhVien.get(boxSinhVien.getSelectedItem()).toString(),listDeTai.get(boxDeTai.getSelectedItem().toString())) == false) {
                JOptionPane.showMessageDialog(null, "Hình như bị trùng rồi", "Thông báo", 1);
            } else {
                phanCong.InsertData(listSinhVien.get(boxSinhVien.getSelectedItem().toString()), listDeTai.get(boxDeTai.getSelectedItem().toString()),txtMaGVHD.getText(), txtMaGVPB.getText(),(Integer)txtDiemGVHD.getValue(),(Integer)txtDiemGVPB.getValue(),textNXGVHD.getText(),textNXGVPB.getText());
            }
            clear();
            ShowData();
            setNull();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tableDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDanhSachMouseClicked
        // TODO add your handling code here:
        int i = tableDanhSach.getSelectedRow();
        for (Map.Entry<String, String> entry : listSinhVien.entrySet()) {
            if (entry.getValue().equals(tableDanhSach.getValueAt(i, 0))) {
                this.boxSinhVien.setSelectedItem(entry.getKey());
            }
        }
        for (Map.Entry<String, Integer > entry : listDeTai.entrySet()) {
            if (entry.getValue() == Integer.parseInt(tableDanhSach.getValueAt(i, 1).toString())) {
                this.boxDeTai.setSelectedItem(entry.getKey());
            }
        }
        this.txtMaGVHD.setText(tableDanhSach.getValueAt(i, 2).toString());
        this.txtMaGVPB.setText(tableDanhSach.getValueAt(i, 3).toString());
        this.txtDiemGVHD.setValue(Integer.parseInt(tableDanhSach.getValueAt(i, 4).toString()));
        this.txtDiemGVPB.setValue(Integer.parseInt(tableDanhSach.getValueAt(i, 5).toString()));
        this.textNXGVHD.setText(tableDanhSach.getValueAt(i, 6).toString());
        this.textNXGVPB.setText(tableDanhSach.getValueAt(i, 7).toString());
    }//GEN-LAST:event_tableDanhSachMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void itemSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSinhVienActionPerformed
        try {
            fmSinhVien f = new fmSinhVien();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(fmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemSinhVienActionPerformed

    private void itemGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGiaoVienActionPerformed
        try {
            fmGiaoVien f = new fmGiaoVien();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(fmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemGiaoVienActionPerformed

    private void itemKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKhoaActionPerformed
        try {
            fmKhoa f = new fmKhoa();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(fmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemKhoaActionPerformed

    private void itemDeTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeTaiActionPerformed
        try {
            fmDeTai f = new fmDeTai();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(fmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemDeTaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fmMain().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDeTai;
    private javax.swing.JComboBox<String> boxSinhVien;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JMenuItem itemDeTai;
    private javax.swing.JMenuItem itemGiaoVien;
    private javax.swing.JMenuItem itemKhoa;
    private javax.swing.JMenuItem itemSinhVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelDanhSach;
    private javax.swing.JPanel panelThongTin;
    private javax.swing.JTable tableDanhSach;
    private javax.swing.JTextArea textNXGVHD;
    private javax.swing.JTextArea textNXGVPB;
    private javax.swing.JSpinner txtDiemGVHD;
    private javax.swing.JSpinner txtDiemGVPB;
    private javax.swing.JTextField txtMaGVHD;
    private javax.swing.JTextField txtMaGVPB;
    // End of variables declaration//GEN-END:variables
}
